---
- name: test
  hosts: 127.0.0.1
  connection: local
  tasks: 
    - name: " aws create the new key"
      ec2_key:
         name: abc_tower
         region: us-east-1
    - name: "Launch ec2 instance"
      ec2: 
         instance_type: t2.micro
         key_name: abc_tower
         image: ami-123456
         count: 1
         group: launch-wizard-7
         vpc_subnet_id:  subnet-37bded6b
         assign_public_ip: yes
         region: us-east-1
